scylladb/scylla-cqlsh

.github/workflows/build-push.yml, bin/cqlsh.py, pylib/setup.py, pyproject.toml, setup.cfg
* change the prefixs for zip imports lookups
* make cython import optional - so source install can work without it
* name the package properly
=> Changes to make scylla-cqlsh easily package inside scylla-java-tools

bin/cqlsh.py, pylib/cqlshlib/test/test_cqlsh_output.py
Now we show the scylla version when connecting
with cqlsh to a scylla cluster
```
❯ cqlsh
Connected to  at 127.0.0.1:9042
[cqlsh 6.0.3.dev0+g5c62c72e04.d20221117 | Scylla 5.2.0~dev-0.20221130.8bc0af9e34fa | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh> SHOW VERSION
[cqlsh 6.0.3.dev0+g5c62c72e04.d20221117 | Scylla 5.2.0~dev-0.20221130.8bc0af9e34fa | CQL spec 3.3.1 | Native protocol v4]
```
Fixes: #9
=> cqlsh.py: show Scylla version on startup/show version

.github/workflows/build-push.yml, pylib/cqlshlib/saferscanner.py
as part of cleanup in pyhton source code,
some of the regex code is using internal resources that was renamed.
Ref: https://github.com/python/cpython/issues/91308
=> Fix code to support python 3.11

dist/redhat/scylla-cqlsh.spec
it's distracting when trying to find build / test errors. 
without this change, rpmbuild complains at see it like:
```
16:44:37  error: bad date in %changelog: initial release
16:44:37  warning: source_date_epoch_from_changelog set but %changelog
is missing
```
=> dist/redhat: add a proper changelog entry

install.sh
this generate unneeded noise into stderr when
using cqlsh bundled with scylla
this configuration is now removed in scylla-core, and not needed in cqlsh.
Fix: #21
=> Remove unneed LC_ALL=en_US.UTF-8

pylib/setup.py, requirements.txt, setup.cfg
we have
```
if sys.version_info < (3, 6):
sys.exit("\ncqlsh requires Python 3.6+\n")
```
in cqlsh.py, so practically, we only support Python 3.6 and up. so drop the support of Python < 3.6 in the metadata. also, "six" package is removed from setup.py and requirements.txt.
=> setup: do not support python2 and remove six

pylib/cqlshlib/__init__.py
Refs scylladb/scylla-tools-java#731
Scylla encryption options are not stored with "normal" options. Because these are 100% intertwined with drivers, and adding stuff there breaks things.
Instead they are extensions. The python driver allows adding extension handlers to print info about these.
This adds a handler, and while the end result will not be the actual cql statement to recreate the table, it at least will provide feedback to the user.
v2:
* format comments
* indentation
=> cqlsh: Add extension handler for "scylla_encryption_options"

scripts/create-relocatable-package.py
The default behavior of tar is to record the uid/gid information, and then restore it. This is problematic if the archive is unpacked as root, since it will create files with the uid/gid of the user who created the archive.
If we build under podman, this normally isn't a problem, since podman runs as root. But under docker we run with the same uid as the caller, and of course it's possible to build without a container at all.
The way I encountered it was when I built both with and without podman. The first build, without podman, copied by uid into the archive. The second build extracted the archive, expanding my uid into podman's subuid range. These files can then no longer be deleted by my original user.
The fix is to add a filter that erases all user information from the tar file as …
=> build: erase uid/gid information from tar archives

.github/workflows/build-push.yml, bin/cqlsh.py, pylib/cqlshlib/test/basecase.py, pylib/cqlshlib/test/cassconnect.py, pylib/cqlshlib/test/run_cqlsh.py, pylib/cqlshlib/test/test_cqlsh_output.py
the change in ad1c8d8e99a03614c8bf136c568fb59b2112bc3f
broke the cloudconf option, since it mixed it with all
the other parameter which are not working together
with the cloud bundle options, and it need to be on
it's own branch of the code.
=> Fix cloudconf handling

.github/workflows/build-push.yml
seems like those builds are not compiling for us,
temporary disable them until we can figure it out
```
error: subprocess-exited-with-error
× Building wheel for scylla-cqlsh (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> [9 lines of output]
cqlshlib/copyutil.c:85563:29: error: implicit declaration of function 'PyInterpreterState_GetID' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
PY_INT64_T current_id = PyInterpreterState_GetID(PyThreadState_Get()->interp);
^
1 error generated.
/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-t6wotqku/overlay/lib/pypy3.9/site-packages/setuptools_scm/git.py:135: UserWarning: "/Users/runner/work/scylla-cqlsh/scylla-cqlsh" is shallow and may cause errors
warnings.warn(f'"{wd.path}" is shallow and may cause …
```
=> Skip pp39-macosx wheel builds

bin/cqlsh.py
Fixes: #44
Signed-off-by: Yaniv Kaul <yaniv.kaul@scylladb.com>
=> cqlsh should use cql v4 by default when connecting #44

bin/cqlsh.py, pylib/cqlshlib/copyutil.py, pylib/cqlshlib/sslhandling.py
This change give us more control when the keys are gonna be loaded, and the passphrses would be asked.
we need to make sure it happen before we start the cqlsh interpeter, and this one the passphrase is being asked from the user only once, and not multiple times on every socket being opened.
Fixes: #46
=> switch from `ssl_options` to `ssl_context`

reloc/build_reloc.sh
to silence the warning from pip:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
poetry 1.5.1 requires build<0.11.0,>=0.10.0, but you have build 1.0.3 which is incompatible.
```
unfortunately, despite that poetry master HEAD now supports build==1.0.3, the latest release of poetry (v1.6.1) still does not include that change. so let's use the version supported by poetry.
=> reloc: install build==0.10.0

pylib/setup.py
this series restructures `get_extensions()`, and also silences the warning like:
```
/tmp/build-env-p23crgfa/lib64/python3.11/site-packages/Cython/Compiler/Main.py:384: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /home/kefu/dev/scylladb/tools/cqlsh/cqlshlib/copyutil.py
tree = Parsing.p_module(s, pxd, full_module_name)
```
=> setup.py: explicitly specify cython's language_level

bin/cqlsh.py
So far if a query is executed during schema changes that takes more then 5sec to be resolved, cqlsh would print a warning and change the return status to failure.
if it's just a warning, we shouldn't be failure the command. especily since after this warning we are waiting without a timeout for schema to be resolved.
Fixes: scylladb/scylla-cqlsh#34
=> stop retruning status_code=2 on schema disagreement

Dockerfile
Seen @ https://github.com/docker-library/python/blob/7899dbafd386ee264bd33574aafcd0f1369b2e21/3.11/slim-bullseye/Dockerfile#L33 Instead of installing all recommended packages, we explicitly mention what we need. It reduces the download of 10's of build-time dependencies.
What I'm not sure of - are we missing features, that are not compiled as deps are not found? (encryption comes to mind).
=> Draft: explicit build-time package dependencies

dist/debian/changelog.template, dist/debian/debian_files_gen.py
this should address the warnings from dpkg-source and
dpkg-parsechangelog, like:
```
dpkg-source: warning: scylla-package/debian/changelog(l3): found end of file where expected more change data or trailer
```
```
dpkg-parsechangelog: warning:     debian/changelog(l3): found end of file where expected more change data or trailer
```
=> dist/debian: add trailer line

bin/cqlsh.py, requirements.txt
In order to use unix domain sockets with python-driver, we have to wrap hostname in UnixSocketEndPoint (like in this example: http://opensource.docs.scylladb.com/master/operating-scylla/admin-tools/maintenance-socket.html#with-python-driver). 
This PR adds checking if hostname is a socket, and if so, it adds wrapping hostname into UnixSocketEndPoint.
I tested it locally using python-driver.
To work correctly it needs 3.26.5 python-driver release (there was no support for unix domain sockets in `WhiteListRoundRobinPolicy` before).
Fixes: https://github.com/scylladb/scylladb/issues/16489
=> Make cqlsh work with unix domain sockets

bin/cqlsh.py, pylib/cqlshlib/test/test_authproviderhandling_config/plain_text_legacy, pylib/cqlshlib/test/test_legacy_auth.py
I have restored the ability to specify a login and password in cqlshrc.
However, I discovered that the features introduced by this commit are not reflected in the documentation.
If you tell me how to make changes to the documentation, I can add a description of using AuthProviders for cqlsh to the documentation.
I also see shortcomings in the tests, for example cqlshlib/test/test_cqlsh_completion.py does not work correctly on an empty database. Therefore, the autotests did not pass completely. But this needs to be corrected with a separate pull request.
Fixes: #73
=> Fix the support for separate credential file

bin/cqlsh.py, pylib/cqlshlib/sslhandling.py
since driver assign automatically `server_hostname` only with ip
and don't use DNS name, cqlsh need to pass it along until
that would be addressed
Fix: https://github.com/scylladb/scylla-cqlsh/issues/75
=> set the hostname in ssl_options.server_hostname when SSL is used

pylib/cqlshlib/sslhandling.py
to align it to the default behavier of previus versions also adds a check to make sure `check_hostname` isn't enabled without enabling `validate` as well.
Fixes: #77
=> cqlshlib/sslhandling: change `check_hostname` deafult to False

bin/cqlsh.py
the import of the version file happens too early, before cqlshlib location is in path, and fails so it works when installing the python package, but no how it's installed/usage by our packaging
moved it to a later stage, so it would start working as expected
Fixes: #81
=> fix cqlsh version print

Dockerfile
since a while the docker seem to have been broken like the following:
```
> [linux/amd64 build-image 2/4] RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get upgrade && apt-get clean && rm -rf /var/lib/apt/lists/*:
2.601 Reading package lists...
3.259 Building dependency tree...
3.410 Reading state information...
3.428 Calculating upgrade...
3.577 The following packages will be upgraded:
3.578   libc-bin libc6
3.581 2 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
3.581 Need to get 3652 kB of archives.
3.581 After this operation, 0 B of additional disk space will be used.
3.581 Do you want to continue? [Y/n] Abort.
------
Dockerfile:13
--------------------
11 |
12 |     # Upgrade packages to the latest, pip as well.
13 | >>> RUN DEBIAN_FRONTEND=noninteractive …
```
=> Dockerfile: noninteractive isn't enough for answering yet on apt-get

pylib/cqlshlib/sslhandling.py
when configuration doesn't define `usercert` or `userkey`
we fail as the following:
```bash
Using CQL driver: <module 'cassandra' from '/opt/scylladb/share/cassandra/libexec/../lib/scylla-driver-3.26.3.zip/cassandra/__init__.py'>
Using connect timeout: 5 seconds
Using 'utf-8' encoding
Using ssl: True
Using cloudconf: None
Traceback (most recent call last):
File "/opt/scylladb/share/cassandra/libexec/cqlsh.py", line 2706, in <module>
main(*read_options(sys.argv[1:], os.environ))
File "/opt/scylladb/share/cassandra/libexec/cqlsh.py", line 2647, in main
shell = Shell(hostname,
^^^^^^^^^^^^^^^
File "/opt/scylladb/share/cassandra/libexec/cqlsh.py", line 490, in __init__
kwargs['ssl_context'] = sslhandling.ssl_settings(hostname, CONFIG_FILE) if ssl else None …
```
=> cqlshlib/sslhandling.py: don't use empty userkey/usercert

pylib/cqlshlib/sslhandling.py
the logic was broken, and could lead to `AttributeError`, like the following:
```
E       AssertionError: Traceback (most recent call last):
E           File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.ccm/scylla-repository/18591/share/cassandra/libexec/cqlsh.py", line 2723, in <module>
E             main(*read_options(sys.argv[1:], os.environ))
E           File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.ccm/scylla-repository/18591/share/cassandra/libexec/cqlsh.py", line 2664, in main
E             shell = Shell(hostname,
E                     ^^^^^^^^^^^^^^^
E           File "/jenkins/workspace/scylla-master/gating-dtest-release/scylla/.ccm/scylla-repository/18591/share/cassandra/libexec/cqlsh.py", line 495, in __init__
E …
```
=> cqlshlib/sslhandling: fix logic of `ssl_check_hostname`

.github/workflows/build-push.yml, pylib/cqlshlib/cql3handling.py, pylib/cqlshlib/test/test_cqlsh_completion.py, pylib/cqlshlib/test/test_cqlsh_output.py
=> Add the tab-completion support of SERVICE_LEVEL statements

bin/cqlsh.py, pylib/cqlshlib/test/test_cqlsh_output.py
Since Scylla 5.2 (https://github.com/scylladb/scylladb/commit/e6ffc220539a05cf7b2a0e37368c27075d809476) a support for server-side DESCRIBE was added. However, cqlsh did not start to use this functionality, since it is only enabled if it detects CQL version at least 4. Scylla did not increase this version number as it doesn't support all of its features, so there is a need for a different detection mechanism for server-side DESCRIBE.
This PR changes the behavior in do_describe: cqlsh will first try to execute the server-side DESCRIBE. If this fails with SyntaxException, meaning that Scylla doesn't support that command, cqlsh falls back to the client-side DESCRIBE behavior. Also I fixed tests to be in line with recent changes to output sent by Scylla.
The other possible solutions were …
=> cqlsh: try server-side DESCRIBE, then client-side 

bin/cqlsh.py
since login command create a new session, we run into an issue when describe was called after login
seem like the row_factory wasn't used
the reason was in the main session we used `execution_profiles` while in the one create in login we did not, which led to copying the wrong values (i.e. like `row_factory` that was needed for server side describe)
this change saves the profiles into the instance, and reuse them when ever a new session is opened
it simplify the code and we could remove a few repetitions of the same logic
=> cqlsh.py: fix server side describe after login command

dist/redhat/scylla-cqlsh.spec
we need to use this global directive:
```
%global debug_package %{nil}
```
otherwise we fail with the following error, since we now don't have any debug files for debug packge:
```
Processing files: scylla-cqlsh-debugsource-6.1.0~dev-0.20240624.c7748f60c0bc.aarch64
error: Empty %files file /jenkins/workspace/scylla-master/next/scylla/tools/cqlsh/build/redhat/BUILD/scylla-cqlsh/debugsourcefiles.list
RPM build errors:
Empty %files file /jenkins/workspace/scylla-master/next/scylla/tools/cqlsh/build/redhat/BUILD/scylla-cqlsh/debugsourcefiles.list
```
=> define the the debug package is empty

dist/debian/control.template, dist/redhat/scylla-cqlsh.spec, scripts/create-relocatable-package.py
so we can use the scylla-python3 driver version
the only problem now, we depend on new dbuild version for using newer version of scylla-driver with cqlsh.
it's really slow down the ability to update new feature that depends on new driver changes (not too many of those)
Ref: https://github.com/scylladb/scylla-python3/pull/40
Fixes: #95
=> remove cassandra from the shiv package

bin/cqlsh.py
To run python executables on scylla-python3, we need to specify /usr/bin/env python3 on shebang, otherwise the script run on /usr/bin/python3.
Fixes #97
=> cqlsh.py: change shebang to /usr/bin/env python3

bin/cqlsh.py, pylib/cqlshlib/test/test_cqlsh_output.py, pylib/cqlshlib/test/test_formatting.py
Attempting to parse a DESCRIBE statement before performing
it forces us to update cqlsh whenever a new element of
the schema that could be described is introduced. We should
try to rely on the server and only in the case of a failure
(when the version of the server is old and it doesn't
recognize the query) should we try to parse it and perform
locally.
Trying to parse it first may lead to rejecting DESCRIBE
statements that would otherwise be valid -- if the grammar
used by cqlsh hasn't caught up with Scylla yet.
Fixes scylladb/scylla-cqlsh#100
=> cqlsh.py: Send DESCRIBE statement to server before parsing

README.md, pylib/setup.py, reloc/build_reloc.sh
in the change to make cqlsh platfrom specific, we introduce an option to disable cython compilation phase.
that option was broken and disable cython completly, which in turn broken the cibuildwheel process, since wheel didn't have any compiled parts any more.
this change switch the disable option to be base on environment variable cause of a lack alternatives
Ref: https://discuss.python.org/t/explicit-optional-cythonization-via-config-setting-post-pep517-and-install-option-deprecation/25379
=> cython: fix the usage of cython

pylib/Dockerfile.ubuntu.py3, pylib/Dockerfile.ubuntu.py37, pylib/Dockerfile.ubuntu.py38
As they part of our SBOM report and not really needed
=> cleanup: remove un-used Dockerfiles

dist/debian/control.template, dist/redhat/scylla-cqlsh.spec
When upgrading for example from `2024.1` to `2025.1` the package name is not identical casuing the upgrade command to fail.
This makes packages upgradable from enterprise.
Related scylladb/scylladb#22420
=> dist: support smooth upgrade from enterprise to source availalbe

bin/cqlsh.py
so far if it wasn't package version of cqlsh, the version from `cqlsh --version` would retun 0.0.0
with this change we'll use setuptools_scm to generate the version string in runtime, it assume it's done within a git repository, otherwise it would fail
Fixes: #124
=> default to setuptools_scm based version when not packaged
